# Generated by Django 4.2.6 on 2023-10-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motores', '0002_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='marca',
            field=models.ManyToManyField(to='motores.marca'),
        ),
    ]
